/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AdmissionStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Text,
  'reviewed' : IDL.Text,
});
export const Address = IDL.Record({
  'street' : IDL.Text,
  'city' : IDL.Text,
  'postalCode' : IDL.Text,
  'state' : IDL.Text,
});
export const Time = IDL.Int;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const OnlineAdmission = IDL.Record({
  'id' : IDL.Nat,
  'status' : AdmissionStatus,
  'heightCm' : IDL.Float64,
  'name' : IDL.Text,
  'packageSelected' : IDL.Text,
  'aadhaar' : IDL.Text,
  'weightKg' : IDL.Float64,
  'medicalHistory' : IDL.Text,
  'address' : Address,
  'timestamp' : Time,
  'paymentMode' : IDL.Text,
  'photo' : ExternalBlob,
});
export const InquiryStatus = IDL.Variant({
  'new' : IDL.Null,
  'closed' : IDL.Text,
  'contacted' : IDL.Text,
});
export const Inquiry = IDL.Record({
  'id' : IDL.Nat,
  'status' : InquiryStatus,
  'serviceInterested' : IDL.Text,
  'name' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAdmission' : IDL.Func([IDL.Nat], [OnlineAdmission], ['query']),
  'getAdmissionsCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getAllAdmissions' : IDL.Func([], [IDL.Vec(OnlineAdmission)], ['query']),
  'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getInquiriesCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getInquiry' : IDL.Func([IDL.Nat], [Inquiry], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'submitAdmission' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
        Address,
        IDL.Text,
        IDL.Text,
        ExternalBlob,
      ],
      [IDL.Nat],
      [],
    ),
  'submitInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'updateAdmissionStatus' : IDL.Func([IDL.Nat, AdmissionStatus], [], []),
  'updateInquiryStatus' : IDL.Func([IDL.Nat, InquiryStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AdmissionStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Text,
    'reviewed' : IDL.Text,
  });
  const Address = IDL.Record({
    'street' : IDL.Text,
    'city' : IDL.Text,
    'postalCode' : IDL.Text,
    'state' : IDL.Text,
  });
  const Time = IDL.Int;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const OnlineAdmission = IDL.Record({
    'id' : IDL.Nat,
    'status' : AdmissionStatus,
    'heightCm' : IDL.Float64,
    'name' : IDL.Text,
    'packageSelected' : IDL.Text,
    'aadhaar' : IDL.Text,
    'weightKg' : IDL.Float64,
    'medicalHistory' : IDL.Text,
    'address' : Address,
    'timestamp' : Time,
    'paymentMode' : IDL.Text,
    'photo' : ExternalBlob,
  });
  const InquiryStatus = IDL.Variant({
    'new' : IDL.Null,
    'closed' : IDL.Text,
    'contacted' : IDL.Text,
  });
  const Inquiry = IDL.Record({
    'id' : IDL.Nat,
    'status' : InquiryStatus,
    'serviceInterested' : IDL.Text,
    'name' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAdmission' : IDL.Func([IDL.Nat], [OnlineAdmission], ['query']),
    'getAdmissionsCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getAllAdmissions' : IDL.Func([], [IDL.Vec(OnlineAdmission)], ['query']),
    'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getInquiriesCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getInquiry' : IDL.Func([IDL.Nat], [Inquiry], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'submitAdmission' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
          Address,
          IDL.Text,
          IDL.Text,
          ExternalBlob,
        ],
        [IDL.Nat],
        [],
      ),
    'submitInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'updateAdmissionStatus' : IDL.Func([IDL.Nat, AdmissionStatus], [], []),
    'updateInquiryStatus' : IDL.Func([IDL.Nat, InquiryStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };