/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Address {
  'street' : string,
  'city' : string,
  'postalCode' : string,
  'state' : string,
}
export type AdmissionStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : string } |
  { 'reviewed' : string };
export type ExternalBlob = Uint8Array;
export interface Inquiry {
  'id' : bigint,
  'status' : InquiryStatus,
  'serviceInterested' : string,
  'name' : string,
  'message' : string,
  'timestamp' : Time,
  'phone' : string,
}
export type InquiryStatus = { 'new' : null } |
  { 'closed' : string } |
  { 'contacted' : string };
export interface OnlineAdmission {
  'id' : bigint,
  'status' : AdmissionStatus,
  'heightCm' : number,
  'name' : string,
  'packageSelected' : string,
  'aadhaar' : string,
  'weightKg' : number,
  'medicalHistory' : string,
  'address' : Address,
  'timestamp' : Time,
  'paymentMode' : string,
  'photo' : ExternalBlob,
}
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAdmission' : ActorMethod<[bigint], OnlineAdmission>,
  'getAdmissionsCount' : ActorMethod<[], bigint>,
  'getAllAdmissions' : ActorMethod<[], Array<OnlineAdmission>>,
  'getAllInquiries' : ActorMethod<[], Array<Inquiry>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getInquiriesCount' : ActorMethod<[], bigint>,
  'getInquiry' : ActorMethod<[bigint], Inquiry>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'submitAdmission' : ActorMethod<
    [
      string,
      string,
      number,
      number,
      string,
      Address,
      string,
      string,
      ExternalBlob,
    ],
    bigint
  >,
  'submitInquiry' : ActorMethod<[string, string, string, string], bigint>,
  'updateAdmissionStatus' : ActorMethod<[bigint, AdmissionStatus], undefined>,
  'updateInquiryStatus' : ActorMethod<[bigint, InquiryStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];